import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ScriptLoadProvider } from "@/context/ScriptLoadContext";
import { TreasureProvider } from "@/context/TreasureContext";
import LayoutClient from "@/components/LayoutClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TreasureProvider>
        <ScriptLoadProvider>
          <LayoutClient className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            {children}
          </LayoutClient>
        </ScriptLoadProvider>
      </TreasureProvider>
    </html>
  );
}
